name: Update Profile

on:
  schedule: # execute every 24 hours
    - cron: '* */24 * * *'
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/update-profile.yaml'

jobs:
  summary-cards:
    name: Summary Cards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}

  wakatime:
    name: WakaTime
    needs: summary-cards
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          SHOW_UPDATED_DATE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_COMMIT: "True"
          # https://github.com/anmol098/waka-readme-stats/issues/337#issuecomment-1324177855
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_SHORT_INFO: "True"
  metrics:
    name: Metrics
    needs: wakatime
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: yanskun
          token: ${{ secrets.GH_TOKEN }}
          template: classic
          config_timezone: Asia/Tokyo
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_followup: yes
          plugin_languages: yes
          plugin_reactions: yes
          plugin_reactions_ignored: github-actions[bot], dependabot[bot]
          plugin_reactions_limit: 200
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_sort: stars
          plugin_people: yes
          plugin_people_types: followers, following, sponsoring, stargazers
          plugin_repositories: yes
          
